# Welcome to Jekyll!

# Dependencies
#markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

paginate:         5

# Custom vars
version:          2.1.0

title: NBlankB
tagline: 블로그
email: ''
description: '현재 블로그 이사중...'
url: 'https://nblankb.github.io/'
baseurl: ''
github_username: NBlankB

# Build settings
#theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
  
futrue: true
timezone: Asia/Seoul
